USE [master];
GO
EXEC sp_configure 'filestream access level', 2;
RECONFIGURE WITH OVERRIDE;
GO
ALTER DATABASE <DBName> SET EMERGENCY;
GO
ALTER DATABASE <DBName> SET SINGLE_USER;
GO
DBCC CHECKDB(<DBName>, REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS;
GO
ALTER DATABASE <DBName> SET MULTI_USER;
GO
